In [8]:
import requests
import numpy as np

#np.zeros((3,4))
#np.ones((2,3,4),dtype=float)
#d = np.arange(10,25,2)
np.linspace(0,2,10)
#print(d)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [13]:
e = np.full((2,3),7)
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [14]:
np.random.random((2,2))

array([[0.42525915, 0.50363419],
       [0.72771133, 0.73402565]])

In [15]:
np.empty((3,2))

array([[1.01582801e+094, 3.54586565e+068],
       [1.57001898e+155, 3.71754479e+177],
       [3.97949006e-315, 0.00000000e+000]])

In [16]:
e.shape

(2, 3)

In [17]:
len(f)

2

In [3]:
import numpy as np
name = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(7,4)


In [4]:
name == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data[name == 'Bob']

array([[ 0.00616849, -0.59053532,  0.32535788, -0.94401667],
       [-0.1203091 ,  0.9178587 , -1.27410942, -0.84952464]])

In [6]:
data

array([[ 0.00616849, -0.59053532,  0.32535788, -0.94401667],
       [ 2.3830213 , -2.17151016, -2.3572172 , -1.48716532],
       [-0.25027057,  0.1219571 ,  0.35146925,  0.27322361],
       [-0.1203091 ,  0.9178587 , -1.27410942, -0.84952464],
       [ 0.46885564, -0.70637553, -0.43326959, -0.52898182],
       [-1.79558807,  0.6222991 , -0.06171493, -0.30191943],
       [-0.13679299, -1.98895548, -2.15958687,  0.11695116]])

In [7]:
x = np.array([1,2,3,4,5,6,7,8,9,0])

x[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
x[3:5]

array([4, 5])

In [12]:
a = x[3:6].copy()

In [13]:
a

array([4, 5, 6])

In [14]:
a[2] = 22

In [15]:
a

array([ 4,  5, 22])

In [18]:
b = x[3:6]
b

array([4, 5, 6])

In [20]:
b[1] = 22
b

array([ 4, 22,  6])

In [21]:
a

array([ 4,  5, 22])

In [22]:
x

array([ 1,  2,  3,  4, 22,  6,  7,  8,  9,  0])

In [24]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
y[1]

array([4, 5, 6])

In [26]:
y[1,2]

6

In [27]:
y[1][2]

6

In [28]:
y[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
y[1,:2]

array([4, 5])

In [30]:
y[0,:3]

array([1, 2, 3])

In [31]:
arr0 = np.arange(20).reshape(4,5)

In [32]:
arr0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
arr0.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [2]:
import numpy as np
x = np.array([1,2,3,4,5,6,7])
y = np.array([22,1,6,2,3,45,6])
np.maximum(x,y)

array([22,  2,  6,  4,  5, 45,  7])

In [3]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [4]:
np.exp(x)

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349, 1096.63315843])

In [5]:
x

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
x**3

array([  1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [11]:
np.log1p(1+x)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015,
       2.07944154, 2.19722458])

In [12]:
np.isnan(x)

array([False, False, False, False, False, False, False])

In [13]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

In [14]:
np.arccos(x)

C:\Users\59972\AppData\Local\Temp/ipykernel_6612/396561874.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(x)


array([ 0., nan, nan, nan, nan, nan, nan])